services:
  postgres:
    image: postgres:17
    container_name: moderation-postgres

    environment:
      POSTGRES_USER: moderation_user
      POSTGRES_PASSWORD: moderation_password
      POSTGRES_DB: moderation_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moderation_user -d moderation_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: