services:

  postgres:
    image: postgres:17
    container_name: moderation-postgres

    environment:
      POSTGRES_USER: moderation_user
      POSTGRES_PASSWORD: moderation_password
      POSTGRES_DB: moderation_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U moderation_user -d moderation_db"
        ]
      interval: 5s
      timeout: 5s
      retries: 5


  api:
    build:
      context: .
      dockerfile: docker/Dockerfile

    container_name: moderation-api

    environment:
      DATABASE_URL: postgresql+psycopg://moderation_user:moderation_password@postgres:5432/moderation_db
      MODEL_RUNTIME: onnx

    volumes:
      - ./models:/app/models:ro

    ports:
      - "8000:8000"

    depends_on:
      postgres:
        condition: service_healthy


  prometheus:
    image: prom/prometheus:latest
    container_name: moderation-prometheus

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

    ports:
      - "9090:9090"

    depends_on:
      - api


  grafana:
    image: grafana/grafana:latest
    container_name: moderation-grafana

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"

    volumes:
      - grafana_data:/var/lib/grafana

      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro

      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro

    ports:
      - "3000:3000"

    depends_on:
      - prometheus


volumes:
  postgres_data:
  prometheus_data:
  grafana_data: