"""create moderation tables

Revision ID: aed1e320725e
Revises: 
Create Date: 2026-09-13 14:26:32.497240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aed1e320725e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('moderation_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('toxic', sa.Boolean(), nullable=False),
    sa.Column('severe_toxic', sa.Boolean(), nullable=False),
    sa.Column('obscene', sa.Boolean(), nullable=False),
    sa.Column('threat', sa.Boolean(), nullable=False),
    sa.Column('insult', sa.Boolean(), nullable=False),
    sa.Column('identity_hate', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('toxic_score', sa.Float(), nullable=False),
    sa.Column('severe_toxic_score', sa.Float(), nullable=False),
    sa.Column('obscene_score', sa.Float(), nullable=False),
    sa.Column('threat_score', sa.Float(), nullable=False),
    sa.Column('insult_score', sa.Float(), nullable=False),
    sa.Column('identity_hate_score', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('corrected_decision', sa.String(length=20), nullable=False),
    sa.Column('corrected_category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('predictions')
    op.drop_table('moderation_preferences')
    op.drop_table('users')
    # ### end Alembic commands ###
